src/App.js, src/components/Manager_member.js, src/components/Manager_page.js, src/server/server.js, src/style/Header.module.css
=> feat: [관리자페이지-회원관리] DB연결

src/components/Header.js
Fix: Header - [운송 예약] 버튼 동작 관련 로직 수정
- 발생 에러: 로그인 성공 이후 [운송 예약] 메뉴 클릭 시 예약 페이지로 이동하지 않고 로그인 페이지로 이동하는 문제
> 해당 기능 부분 함수화 하여 에러 수정 완료
=> fix: Header 운송예약 라우팅 관련 로직 수정

src/components/Manager_header.js, src/components/Manager_vehicle.js, src/components/Manager_vehicle_add.js, src/style/Manager_header.module.css, src/style/Manager_vehicle.module.css, src/style/Manager_vehicle_add.module.css
관리자페이지( 헤더, 차량관리 및 등록 페이지) 새로 추가합니다
=> feat: [관리자페이지-헤더, 차량관리 및 등록]페이지 추가

src/components/Manager_main.js, src/components/Manager_member.js, src/components/Manager_member_detail.js, src/style/Manager_member.module.css
=> fix: ManagerHeader 컴포넌트 추가, 디자인 수정

src/components/Manager_page.js, src/components/Manager_vehicle.js, src/components/Manager_vehicle_add.js, src/server/server.js
=> feat: [관리자페이지-운송차량관리] 차량목록 조회 기능 추가

src/App.js, src/components/Manager_vehicle.js, src/components/Manager_vehicle_add.js, src/components/Mypage.jsx, src/components/Mypage_confirm.js, src/components/Mypage_info.js, src/style/Mypage.module.css, src/style/Mypage_confirm.module.css, src/style/Mypage_info.module.css
> 차량 등록 성공 시 차량 목록에 추가된 차량이 바로 보여지지 않는 상태 수정
=> feat: [관리자페이지-차량관리] 차량 등록 후 목록 출력 로직 추가

src/components/Manager_member_detail.js, src/style/Manager_member.module.css, src/style/Manager_member_detail.module.css, src/style/Manager_reserv.module.css, src/style/Manager_vehicle.module.css, src/style/Manager_vehicle_add.module.css
=> style: 관리자 페이지 디자인 수정

src/components/Manager_vehicle.js, src/components/Manager_vehicle_add.js, src/server/server.js, src/style/Manager_vehicle.module.css
=> feat: 등록 차량 삭제 기능 추가

src/style/Manager_member.module.css, src/style/Manager_reserv.module.css, src/style/Manager_vehicle.module.css, src/style/Reservation.module.css
> 버튼 hover 시 transition 값 0.3s => 0.2s로 변경 / color var(--cancel-color) 로 변경
> 관리자 페이지 예약 상세 내역 표시 부분 box-shadow 속성 추가
=> style: 관리자페이지 X버튼, 예약 컨텐츠 박스 스타일 수정

src/style/Manager_notice.module.css
> 다른 탭 메뉴 테이블과 동일하게 테이블 사이즈 1200px로 수정
> 삭제버튼 hover 시 색상 --cancel-color로 변경
> 수정/삭제 버튼 transition 0.3s에서 0.2s로 변경
=> style: 공지사항관리 페이지 디자인 수정

src/components/Manager_review.js
feat: [관리자페이지-이용자평가내역] 페이지 파일 추가
=> feat: [관리자페이지-이용자평가내역] 페이지 파일 추가

src/components/Footer.js, src/style/Footer.module.css
=> feat: [푸터-개인정보처리방침 모달창]

src/components/Manager_review.js, src/style/Manager_notice.module.css, src/style/Manager_review.module.css
관리자페이지 공지사항 등록버튼 위치 수정, 이용자 평가내역 디자인 통일한거 올립니다!
=> style: [관리자페이지-공지사항등록버튼, 이용자평가내역]디자인 수정

package-lock.json, package.json, src/App.js, src/components/Batterystatus.js, src/components/Control_main.js, src/components/Currenttime.js, src/components/Footer.js, src/components/Header.js, src/components/Join.js, src/components/Login.js, src/style/Control_main.module.css, src/style/Footer.module.css, src/style/Login.module.css, src/style/Toast.css, yarn.lock
> Login.js, Join.js, Header.js 파일 내 기존 alert으로 안내하던 부분 toast로 기능 변경
=> feat: alert -> toast 기능 변경

src/App.js, src/components/Header.js, src/components/Manager_page.js, src/components/Manager_reserv.js, src/server/server.js, src/style/Manager_reserv.module.css
> [관리자페이지 - 예약관리] DB 연결
> 테이블 디자인 조정
=> feat: 예약관리 DB 연결 및 스타일 조정

src/components/Customer_help_center.jsx, src/components/Customer_rating.js, src/components/Customer_review_list.jsx, src/style/Customer_faq.module.css, src/style/Customer_rating.module.css, src/style/Customer_review_list.module.css
고객센터 디자인 수정하고 이용자평가 하단 고객센터 번호 삭제했습니다 footer에 고객센터 정보 생겨서 뺐습니다!
=> style: [고객센터-디자인통일, 하단고객센터번호삭제]디자인 수정

src/components/Header.js
> merge 이후 헤더 탭메뉴 중 [운송예약] 버튼 클릭 시 로그인 여부에 관계 없이 예약 페이지로 넘어가는 문제 해결
=> fix: merge 이후 [운송예약] 라우팅 문제 해결

src/components/Manager_member.js, src/components/Manager_notice.js, src/components/Manager_notice_add.js, src/components/Manager_page.js, src/components/Manager_reserv.js, src/server/server.js, src/style/Manager_notice_add.module.css
> [관리자페이지 - 공지사항 관리] 공지 글 등록 기능 추가
=> feat: [공지사항관리] 공지등록 기능 추가

src/components/Manager_notice.js, src/components/Manager_notice_add.js, src/server/server.js, src/style/Manager_notice.module.css
> [관리자페이지 - 공지사항관리] 공지글 삭제버튼 삭제 기능 추가
> DB에서 불러온 게시글이 (DB에 데이터가) 없는 경우 "공지사항이 없습니다" 출력
=> feat: [공지사항관리] 삭제버튼 기능 추가

src/components/Manager_member.js, src/server/server.js, src/style/Manager_member.module.css
> [관리자페이지 - 회원관리] 삭제 버튼으로 회원 삭제하는 기능 추가
> 등록된 회원이 없을 경우 "등록된 회원이 없습니다." 출력
=> feat: [회원관리] 회원 삭제 기능 추가

src/components/Control_main.js, src/style/Control_main.module.css, src/style/Main_page.module.css
우선 차량관제화면 디자인 깨짐 수정한거랑 메인페이지 운송예약단계 텍스트부분 사이즈 조정한거 올립니다
=> style: [차량관제화면-디자인깨짐수정, 메인페이지-텍스트수정]

package-lock.json, package.json, src/components/Confirm_func.jsx, src/components/Manager_member.js, src/components/Manager_notice.js, src/components/Manager_vehicle.js, src/style/Confirm_func.css, src/style/Control_main.module.css, yarn.lock
> 삭제 버튼 클릭 시 삭제를 한번 더 확인하는 안내 창 표시
> "삭제" 버튼 클릭 시 삭제 진행 후 삭제완료 토스트 팝업
> "돌아가기" 버튼 클릭 시 기존 화면으로 돌아감
=> feat: [관리자페이지] 삭제 확인창 추가

src/components/Control_main.js, src/style/Control_main.module.css
=> style: [차량관제화면-사이드메뉴 버튼 수정]

src/components/Customer_rating.js, src/components/Customer_review_list.jsx, src/components/Manager_vehicle_add.js, src/components/Mypage.jsx, src/components/Reservation.js, src/server/server.js
> [마이페이지] DB 연결 완료
> [운송예약] 차량 명 "0호차" 형식으로 변경
=> feat: [마이페이지] DB 연결, [운송예약] 선택차량 명 변경

src/components/Confirm_func.jsx, src/components/Manager_member.js, src/components/Manager_notice.js, src/components/Manager_vehicle.js, src/server/server.js
> [회원관리] 예약이 존재하는 아이디 삭제 요청 시 삭제 불가 안내 표시
> [관리자 페이지] 항목 삭제 후 변경 사항이 바로 반영되지 않던 오류 수정
=> feat: [회원관리] 예약 존재 아이디 삭제 불가 안내 표시

src/components/Customer_FAQ.js, src/components/Customer_help_center.jsx, src/components/Customer_review_list.jsx, src/components/Mypage.jsx, src/components/Mypage_confirm.js, src/components/Mypage_info.js, src/components/Notice_main.js, src/style/Customer_faq.module.css, src/style/Customer_review_list.module.css, src/style/Mypage_confirm.module.css, src/style/Mypage_info.module.css, src/style/Notice_main.module.css
[고객센터, 마이페이지- 넘버삭제, 이용자평가버튼 이동 및 수정]
=> style: [고객센터, 마이페이지- 넘버삭제, 이용자평가버튼 이동 및 수정]

src/components/Login.js, src/style/Join.module.css, src/style/Login.module.css
=> style: [회원가입-디자인 수정]

src/components/Customer_rating.js, src/components/Customer_review_list.jsx, src/components/Mypage.jsx, src/components/Mypage_confirm.js, src/server/server.js, src/style/Mypage.module.css, src/style/Mypage_confirm.module.css
> 예약 건에 대한 리뷰 등록 기능 추가
> 이미 리뷰가 등록된 예약은 "서비스 평가하기" 버튼 ==> "평가 완료"  로 변경되어 리뷰 재등록 불가능
=> feat: [마이페이지-예약내역] 리뷰 등록 관련 기능 추가

src/components/Customer_review_list.jsx, src/components/Manager_page.js, src/components/Manager_review.js, src/components/Notice_detail.js, src/components/Notice_main.js, src/server/server.js
> [공지사항] 글 목록, 글 상세 페이지 라우팅 작업 및 DB 연결 완료
> [관리자 페이지 - 이용자 평가 내역] DB 연결
=> feat: [공지사항] 목록/상세 페이지 DB 연결, [관리자페이지-리뷰] DB 연결

src/components/Manager_notice.js, src/components/Manager_notice_modify.js, src/server/server.js
=> feat: [관리자페이지-공지사항] 공지글 수정기능 추가

src/components/Manager_main.js, src/server/server.js
=> feat: [관리자페이지 - Home] 데이터 출력

package-lock.json, package.json, src/components/Control_main.js
> 충전소 정보 제공 시스템 API 연결
> API로 호출한 데이터를 이용한 충전소 위치 마커로 표시
=> feat: 충전소 정보 제공 API로 받아온 데이터 지도에 마커 표시

src/components/Main_page.js
=> style: [메인페이지-텍스트 수정]

src/App.js, src/components/Control_main.js, src/components/Main_page.js, src/server/server.js, src/style/Control_main.module.css
> [관제화면] 지도 중심 변경에 따른 주소 출력 기능 추가
> [관제화면] ControlMain Hook 사용 구조 변경
> [관제화면] useState를 이용한 카카오 맵 객체 저장 >>> 객체 재사용 가능
> [메인페이지] "서비스 더보기", "운송 예약하기" 라우팅
=> feat: [관제화면] 기능추가/[메인페이지] 라우팅 작업

src/components/Control_main.js, src/style/Control_main.module.css
> 충전소 목록 표시
> 충전소 목록에서 충전소 선택 시 선택된 충전소 정보 안내 및 해당 충전소 위치로 지도 이동
=> feat: [관제화면] 충전소 목록 기능 추가

src/components/Manager_member.js, src/components/Manager_member_detail.js, src/style/Manager_member.module.css
> 회원 상세 조회 데이터 연결
> 회원 정보 테이블 수정
=> feat: [관리자페이지]회원 상세정보 조회
